### ISSUE TITLE
Import JSTS from external package

### ISSUE THREAD

**Issue by friedjoff** [geops/ole2#60]
Controls that use JSTS code should not import JSTS files by referencing the full path to the node_modules directory. Instead Webpack should import and compile JSTS files by referencing the JSTS package. Right now this will not work, because Webpack will not compile files from external packages. Maybe use and configure [babel-loader](https://github.com/babel/babel-loader).

**Comment by friedjoff** [comment]
See [buffer.js](https://github.com/geops/ole2/blob/dfe4f09b753bb04190f20c792295f041c8f474cd/src/control/buffer.js#L1) for an example.

**Comment by mhaertwig** [comment]
:+1:
We could add a check to `TopologyControl` if `jsts` is defined.
