### ISSUE TITLE
Release and distribute to NPM

### ISSUE THREAD

**Issue by iteratoruk** [geops/ole2#9]
Are there any plans to do a release to a CDN, such as cdnjs and npm?

**Comment by lb1c** [comment]
@mhaertwig Since we're using travis-ci the releasing to npm would be possible without to much overhead. What's your opinion on this?

https://docs.travis-ci.com/user/deployment/npm/

**Comment by mhaertwig** [comment]
I didn't plan it so far since ole2 is still in an early state. But why not!?
